 plugins:
  - jekyll-redirect-from
 title: Forwardpage
 redirect_to: https://194.95.221.67
## Github überschreibt folgende Datensätze immer:
#  lsi: false
# safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge
#
   
